#!/bin/bash

# Get the Python file name from the environment variable
pyfile=$PYFILE

# Check if the PYFILE variable is set
if [ -z "$pyfile" ]; then
    echo "Error: PYFILE environment variable not set."
    exit 1
fi

# Check if the Python file exists
if [ ! -f "$pyfile" ]; then
    echo "Error: Python file '$pyfile' does not exist."
    exit 1
fi

# Run the Python script
python3 "$pyfile"

